server:
  port: 8084

wechat:
  ip: http://zhangjf.iask.in:11710
  appid: wx06668e4d74c358a7
  secret: 4b58a9aac888b22c0c23d1e64599fb60

swagger:
  scan: com.example.wechat.modules
  title: 用户service API
  description: 用户service API
  version: 1.0.0

spring:
  redis:
    database: 0
    host: 192.168.10.217
    port: 6379
    password: ky@2018!   # 密码（默认为空）
    timeout: 6000  # 连接超时时长（毫秒）
    pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
